CREATE DATABASE ShoesApplicationDatabase;
USE ShoesApplicationDatabase;

CREATE TABLE Users(
Id INT PRIMARY KEY IDENTITY(1,1),
Username NVARCHAR(50) NOT NULL UNIQUE,
FullName NVARCHAR(100) NOT NULL,
PhoneNumber NVARCHAR(15) NULL,
Email NVARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE Brands(
Id INT PRIMARY KEY IDENTITY(1,1),
[Name] NVARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE Sizes(
Id INT PRIMARY KEY IDENTITY(1,1),
EU DECIMAL(5,2) NOT NULL,
US DECIMAL(5,2) NOT NULL,
UK DECIMAL(5,2) NOT NULL,
CM DECIMAL(5,2) NOT NULL,
[IN] DECIMAL(5,2) NOT NULL
);

CREATE TABLE Shoes(
Id INT PRIMARY KEY IDENTITY(1,1),
Model NVARCHAR(30) NOT NULL,
Price DECIMAL(10,2) NOT NULL,
BrandId INT NOT NULL,
FOREIGN KEY (BrandId) REFERENCES Brands(Id)
);

CREATE TABLE ShoesSizes(
ShoeId INT NOT NULL,
SizeId INT NOT NULL,
PRIMARY KEY (ShoeId, SizeId),
FOREIGN KEY (ShoeId) REFERENCES Shoes(Id),
FOREIGN KEY (SizeId) REFERENCES Sizes(Id)
);

CREATE TABLE Orders(
Id INT PRIMARY KEY IDENTITY(1,1),
ShoeId INT NOT NULL,
SizeId INT NOT NULL,
UserId INT NOT NULL,
FOREIGN KEY (ShoeId) REFERENCES Shoes(Id),
FOREIGN KEY (SizeId) REFERENCES Sizes(Id),
FOREIGN KEY (UserId) REFERENCES Users(Id)
);