-- Delete CONSTRAINTS
ALTER TABLE [Users] DROP CONSTRAINT PK_Users

-- Add PRIMARY KEY
ALTER TABLE [Users] ADD CONSTRAINT PK_Users PRIMARY KEY(Id)

ALTER TABLE [Users] ADD CONSTRAINT CHK_Username CHECK(LEN(Username) >=3)

ALTER TABLE [Users] ADD CONSTRAINT UQ_Username UNIQUE(Username)

sp_help [Users]